# Generated by Django 5.0.6 on 2024-05-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_name', models.CharField(max_length=200)),
                ('Email_Address', models.EmailField(max_length=200)),
                ('File_To_Upload', models.FileField(max_length=254, upload_to=None)),
            ],
        ),
    ]
