# Generated by Django 5.0.6 on 2024-05-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_deployment_file_to_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='File_To_Upload',
            field=models.FileField(default='hi', upload_to=''),
        ),
    ]
